# Generated by Django 3.1.1 on 2020-09-06 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=60, verbose_name='Адрес Института')),
                ('name_education', models.CharField(max_length=60, verbose_name='название Института')),
            ],
            options={
                'verbose_name': 'Образование',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lesson', models.CharField(max_length=35, verbose_name='название предмета')),
                ('number_lesson', models.IntegerField(default=0, verbose_name='Номер аудитории')),
                ('adress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studens.education', verbose_name='Образование')),
            ],
            options={
                'verbose_name': 'Урок',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='имя преподавателя')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('history', models.PositiveSmallIntegerField(default=0, verbose_name='Стаж')),
            ],
            options={
                'verbose_name': 'Учитель',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(default=0, verbose_name='Оценка за предмет')),
                ('sr_rate', models.FloatField(default=0.0, verbose_name='Среднее значение')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studens.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Оценка',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ManyToManyField(to='studens.Teacher', verbose_name='Учитель'),
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_visits', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studens.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Посещаемость',
            },
        ),
    ]
