# Generated by Django 3.1.1 on 2020-09-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='facultet',
            field=models.TextField(default=0, verbose_name='Факультет'),
            preserve_default=False,
        ),
    ]
