# Generated by Django 3.1.1 on 2020-09-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studens', '0003_auto_20200907_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='vote',
            field=models.IntegerField(default=0, verbose_name='Количество оценок'),
        ),
    ]
