# Generated by Django 3.1.1 on 2020-09-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studens', '0004_rate_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='sum_rating',
            field=models.IntegerField(default=0, verbose_name='Сумма оценок'),
        ),
    ]
