# Generated by Django 3.1.1 on 2020-09-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studens', '0005_rate_sum_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='sr_rate',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='sum_rating',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='vote',
        ),
    ]
